version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000 --timeout 180
    volumes:
      - django-on-docker_static_volume:/home/app/web/staticfiles
      - django-on-docker_media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - django-on-docker_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - django-on-docker_static_volume:/home/app/web/staticfiles
      - django-on-docker_media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  django-on-docker_postgres_data:
    external: true
  django-on-docker_static_volume:
    external: true
  django-on-docker_media_volume:
    external: true